version: '3.7'

services:
  application:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/ymym24.online:/etc/nginx/certs:ro
    ports:
      - "443:443"        # HTTPS (TCP)
      - "443:443/udp"    # QUIC/HTTP3 (UDP)
    networks:
      - app-network

networks:
  app-network:
    driver: bridge