server:
  port: 8080
  shutdown: graceful

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
