name: Deploy Spring Boot Application

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Gradle 캐싱
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
            
      # 3. Java 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 4. Gradle 빌드
      - name: Build with Gradle
        run: |
          ./gradlew clean build
          mkdir -p deploy
          cp build/libs/classroom-assignment-0.0.1-SNAPSHOT.jar deploy/app.jar


      # 5. 빌드 결과 확인
      - name: List build directory
        run: ls -la build/libs/

      # 6. 서버로 전송
      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./deploy/app.jar
          target: /app/
