name: Deploy to AWS EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Repository Checkout
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Build JAR File (Gradle Example)
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21' # Java 21로 설정
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    # 3. Deploy to AWS EC2
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: scp -i ${{ secrets.SSH_PRIVATE_KEY }} build/libs/*.jar ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/app/deploy/app.jar
